/**
 * 1-Click Deploy Wizard
 * 6-step guided deployment: Select Bundle → Choose Host → Configure → Review → Pipeline → Complete
 * AiGovOps palette: navy #1B3A6B, teal #01696F
 */
import { useState, useRef, useCallback, useEffect } from "react";
import { useCopyToClipboard } from "@/hooks/use-copy-to-clipboard";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Apple,
  Check,
  CheckCircle2,
  ChevronRight,
  ClipboardCopy,
  Eye,
  EyeOff,
  Loader2,
  Lock,
  RotateCcw,
  Server,
  X,
  XCircle,
  AlertTriangle,
  ArrowLeft,
  Rocket,
  Cloud,
} from "lucide-react";
import { resolveIcon } from "@/lib/icon-map";
import { useI18n } from "@/lib/i18n";
import { API_BASE } from "@/lib/queryClient";
import { celebrate } from "@/lib/celebrations";
import { playSound } from "@/lib/sound-engine";
import {
  oneClickBundles,
  HOST_TARGETS,
  HOST_REQUIRED_INPUTS,
  PIPELINE_STAGES,
  type MarketplaceEntry,
  type DeployTarget,
  type InputField,
  type PipelineStep,
} from "@/data/marketplace-unified";
import type { Translations } from "@/lib/i18n";

// ── Types ────────────────────────────────────────────────────────────────────

type WizardStep = 1 | 2 | 3 | 4 | 5 | 6;

type StageStatus = "pending" | "running" | "passed" | "failed" | "skipped";

interface PipelineStageState {
  step: PipelineStep;
  status: StageStatus;
  message?: string;
  elapsedMs?: number;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function hostIcon(hostId: string): React.ReactNode {
  if (hostId === "macos") return <Apple className="h-4 w-4" />;
  if (hostId === "generic-vps") return <Server className="h-4 w-4" />;
  return <Cloud className="h-4 w-4" />;
}

function buildYaml(
  bundle: MarketplaceEntry,
  hostId: string,
  inputs: Record<string, string>
): string {
  const safeInputs = Object.entries(inputs)
    .map(([k, v]) => `  ${k}: "${v.replace(/"/g, '\\"')}"`)
    .join("\n");

  const agents = (bundle.bundleAgents || []).map((a) => `  - id: ${a}`).join("\n");
  const connectors = (bundle.bundleConnectors || []).map((c) => `  - id: ${c}`).join("\n");

  return `# OpenClaw 1-Click Deploy Manifest
# Generated by AiGovOps Guided Install
# Bundle: ${bundle.name}
# Host:   ${hostId}
# Date:   ${new Date().toISOString()}

bundle:
  id: ${bundle.id}
  version: ${bundle.version || "1.0.0"}

host:
  target: ${hostId}

inputs:
${safeInputs || "  # (no inputs provided)"}

agents:
${agents || "  # (none)"}

connectors:
${connectors || "  # (none)"}

pipeline:
  smoke_test: true
  stress_test: true
  dry_run: true
  require_permission_gate: true
  audit_log: true
`;
}

/** SHA-256 of a string (browser crypto) */
async function sha256(text: string): Promise<string> {
  const buf = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(text)
  );
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// ── Step Indicator ────────────────────────────────────────────────────────────

const STEP_LABELS = [
  "deployStepBundle",
  "deployStepHost",
  "deployStepInputs",
  "deployStepReview",
  "deployStepPipeline",
  "deployStepComplete",
] as const;

const STEP_FALLBACKS = [
  "Select Bundle",
  "Choose Host",
  "Configure",
  "Review",
  "Deploy",
  "Complete",
];

function StepIndicator({
  current,
  t,
}: {
  current: WizardStep;
  t: Translations;
}) {
  return (
    <ol className="flex items-center justify-center gap-1 mb-8 flex-wrap" aria-label="Wizard steps">
      {STEP_LABELS.map((key, i) => {
        const step = (i + 1) as WizardStep;
        const isActive = step === current;
        const isDone = step < current;

        return (
          <li key={step} className="flex items-center" aria-current={isActive ? "step" : undefined}>
            <div
              className={[
                "flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold transition-all",
                isActive
                  ? "bg-[#01696F] text-white shadow-md"
                  : isDone
                  ? "bg-[#01696F]/20 text-[#01696F] dark:text-teal-400"
                  : "bg-muted text-muted-foreground",
              ].join(" ")}
              aria-label={`Step ${step}: ${t[key] || STEP_FALLBACKS[i]}${isDone ? " (completed)" : isActive ? " (current)" : ""}`}
            >
              {isDone ? (
                <Check className="h-3 w-3" aria-hidden="true" />
              ) : (
                <span className="w-4 text-center" aria-hidden="true">{step}</span>
              )}
              <span className="hidden sm:inline" aria-hidden="true">
                {t[key] || STEP_FALLBACKS[i]}
              </span>
            </div>
            {i < 5 && (
              <ChevronRight className="h-3 w-3 text-muted-foreground mx-0.5" aria-hidden="true" />
            )}
          </li>
        );
      })}
    </ol>
  );
}

// ── Step 1: Select Bundle ────────────────────────────────────────────────────

function BundleCard({
  bundle,
  selected,
  onSelect,
}: {
  bundle: MarketplaceEntry;
  selected: boolean;
  onSelect: () => void;
}) {
  const Icon = resolveIcon(bundle.icon);
  const categoryColors: Record<string, string> = {
    "starter-bundle": "bg-blue-500/10 text-blue-600 dark:text-blue-400",
    "enterprise-bundle": "bg-purple-500/10 text-purple-600 dark:text-purple-400",
    "privacy-bundle": "bg-green-500/10 text-green-600 dark:text-green-400",
  };

  return (
    <button
      type="button"
      data-testid={`bundle-card-${bundle.id}`}
      onClick={onSelect}
      className={[
        "w-full text-left rounded-xl border-2 p-4 transition-all hover:border-[#01696F] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#01696F]",
        selected
          ? "border-[#01696F] bg-[#01696F]/5 shadow-md"
          : "border-border bg-card hover:bg-muted/30",
      ].join(" ")}
    >
      <div className="flex items-start gap-3">
        <div
          className={[
            "p-2 rounded-lg shrink-0",
            selected ? "bg-[#01696F] text-white" : "bg-muted text-muted-foreground",
          ].join(" ")}
        >
          <Icon className="h-5 w-5" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-semibold text-sm">{bundle.name}</span>
            {bundle.featured && (
              <Badge variant="secondary" className="text-[10px]">
                Featured
              </Badge>
            )}
            <Badge
              variant="outline"
              className={`text-[10px] ${categoryColors[bundle.category] || ""}`}
            >
              {bundle.category.replace("-bundle", "")}
            </Badge>
          </div>
          <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
            {bundle.description}
          </p>
          <div className="flex gap-4 mt-2 text-xs text-muted-foreground">
            <span>
              <strong>{bundle.bundleAgents?.length ?? 0}</strong> agents
            </span>
            <span>
              <strong>{bundle.bundleConnectors?.length ?? 0}</strong> connectors
            </span>
            {bundle.estimatedCost && (
              <span className="text-[#01696F] font-medium">{bundle.estimatedCost}</span>
            )}
          </div>
        </div>
        {selected && (
          <CheckCircle2 className="h-5 w-5 text-[#01696F] shrink-0" aria-hidden="true" />
        )}
      </div>
    </button>
  );
}

function Step1SelectBundle({
  selected,
  onSelect,
  onNext,
  t,
}: {
  selected: MarketplaceEntry | null;
  onSelect: (b: MarketplaceEntry) => void;
  onNext: () => void;
  t: Translations;
}) {
  return (
    <div className="space-y-4">
      <div>
        <h2 className="text-lg font-semibold text-[#1B3A6B] dark:text-slate-100">
          {t.deployStepBundle || "Select Bundle"}
        </h2>
        <p className="text-sm text-muted-foreground">
          Choose a pre-built bundle to deploy. Each bundle includes agents, connectors, and a
          recommended host target.
        </p>
      </div>
      <div className="space-y-3">
        {oneClickBundles.map((bundle) => (
          <BundleCard
            key={bundle.id}
            bundle={bundle}
            selected={selected?.id === bundle.id}
            onSelect={() => onSelect(bundle)}
          />
        ))}
        {/* Custom — Coming Soon */}
        <div
          data-testid="bundle-card-custom"
          className="w-full text-left rounded-xl border-2 border-dashed border-border p-4 opacity-60 cursor-not-allowed"
        >
          <div className="flex items-start gap-3">
            <div className="p-2 rounded-lg bg-muted text-muted-foreground shrink-0">
              <Rocket className="h-5 w-5" />
            </div>
            <div className="flex-1">
              <div className="flex items-center gap-2">
                <span className="font-semibold text-sm">Custom Bundle</span>
                <Badge variant="outline" className="text-[10px] bg-yellow-500/10 text-yellow-600">
                  Coming Soon
                </Badge>
              </div>
              <p className="text-xs text-muted-foreground mt-1">
                Pick individual agents and connectors to build your own custom bundle.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="flex justify-end pt-2">
        <Button
          data-testid="step1-next"
          disabled={!selected}
          onClick={onNext}
          className="bg-[#01696F] hover:bg-[#01696F]/90 text-white"
        >
          Continue
          <ChevronRight className="h-4 w-4 ml-1" />
        </Button>
      </div>
    </div>
  );
}

// ── Step 2: Choose Host Target ───────────────────────────────────────────────

function Step2ChooseHost({
  bundle,
  selected,
  onSelect,
  onNext,
  onBack,
  t,
}: {
  bundle: MarketplaceEntry;
  selected: DeployTarget | null;
  onSelect: (dt: DeployTarget) => void;
  onNext: () => void;
  onBack: () => void;
  t: Translations;
}) {
  const targets = bundle.deployTargets?.filter((dt) => dt.supported) ?? [];

  return (
    <div className="space-y-4">
      <div>
        <h2 className="text-lg font-semibold text-[#1B3A6B] dark:text-slate-100">
          {t.deployStepHost || "Choose Host"}
        </h2>
        <p className="text-sm text-muted-foreground">
          Select where to deploy <strong>{bundle.name}</strong>.
        </p>
      </div>
      <div className="space-y-2">
        {targets.map((dt) => {
          const hostMeta = HOST_TARGETS.find((h) => h.id === dt.hostId);
          if (!hostMeta) return null;
          const isSelected = selected?.hostId === dt.hostId;

          return (
            <button
              key={dt.hostId}
              type="button"
              data-testid={`host-target-${dt.hostId}`}
              onClick={() => onSelect(dt)}
              className={[
                "w-full text-left rounded-xl border-2 p-4 transition-all hover:border-[#01696F] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#01696F]",
                isSelected
                  ? "border-[#01696F] bg-[#01696F]/5 shadow-md"
                  : "border-border bg-card hover:bg-muted/30",
              ].join(" ")}
            >
              <div className="flex items-center gap-3">
                <div
                  className={[
                    "p-2 rounded-lg shrink-0",
                    isSelected ? "bg-[#01696F] text-white" : "bg-muted text-muted-foreground",
                  ].join(" ")}
                >
                  {hostIcon(dt.hostId)}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-semibold text-sm">{hostMeta.name}</span>
                    {dt.oneClickAvailable && (
                      <Badge
                        variant="secondary"
                        className="text-[10px] bg-[#01696F]/10 text-[#01696F] dark:text-teal-400"
                      >
                        1-Click
                      </Badge>
                    )}
                  </div>
                  <div className="flex gap-4 mt-0.5 text-xs text-muted-foreground">
                    <span>~{dt.estimatedMinutes} min deploy</span>
                    {dt.notes && <span className="italic">{dt.notes}</span>}
                  </div>
                </div>
                {isSelected && (
                  <CheckCircle2 className="h-5 w-5 text-[#01696F] shrink-0" aria-hidden="true" />
                )}
              </div>
            </button>
          );
        })}
      </div>
      <div className="flex justify-between pt-2">
        <Button variant="outline" onClick={onBack} data-testid="step2-back">
          <ArrowLeft className="h-4 w-4 mr-1" />
          Back
        </Button>
        <Button
          data-testid="step2-next"
          disabled={!selected}
          onClick={onNext}
          className="bg-[#01696F] hover:bg-[#01696F]/90 text-white"
        >
          Continue
          <ChevronRight className="h-4 w-4 ml-1" />
        </Button>
      </div>
    </div>
  );
}

// ── Step 3: Collect Inputs ───────────────────────────────────────────────────

function FieldInput({
  field,
  value,
  onChange,
  error,
}: {
  field: InputField;
  value: string;
  onChange: (v: string) => void;
  error?: boolean;
}) {
  const [showSecret, setShowSecret] = useState(false);

  const labelNode = (
    <label
      htmlFor={`field-${field.id}`}
      className="text-sm font-medium flex items-center gap-1.5"
    >
      {field.secret && <Lock className="h-3 w-3 text-muted-foreground" />}
      {field.label}
      {field.required && <span className="text-red-500">*</span>}
    </label>
  );

  let inputNode: React.ReactNode;

  if (field.type === "select" && field.options) {
    inputNode = (
      <Select
        value={value || field.default || ""}
        onValueChange={onChange}
      >
        <SelectTrigger
          id={`field-${field.id}`}
          data-testid={`input-${field.id}`}
          className={error ? "border-red-500" : ""}
        >
          <SelectValue placeholder={field.placeholder} />
        </SelectTrigger>
        <SelectContent>
          {field.options.map((opt) => (
            <SelectItem key={opt} value={opt}>
              {opt}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    );
  } else if (field.type === "password") {
    inputNode = (
      <div className="relative">
        <Input
          id={`field-${field.id}`}
          data-testid={`input-${field.id}`}
          type={showSecret ? "text" : "password"}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={field.placeholder}
          className={`pr-9 ${error ? "border-red-500" : ""}`}
          autoComplete="off"
        />
        <button
          type="button"
          onClick={() => setShowSecret((s) => !s)}
          className="absolute inset-y-0 right-2 flex items-center text-muted-foreground hover:text-foreground"
          aria-label={showSecret ? "Hide" : "Show"}
        >
          {showSecret ? (
            <EyeOff className="h-4 w-4" />
          ) : (
            <Eye className="h-4 w-4" />
          )}
        </button>
      </div>
    );
  } else if (field.type === "number") {
    inputNode = (
      <Input
        id={`field-${field.id}`}
        data-testid={`input-${field.id}`}
        type="number"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={field.placeholder}
        className={error ? "border-red-500" : ""}
      />
    );
  } else {
    inputNode = (
      <Input
        id={`field-${field.id}`}
        data-testid={`input-${field.id}`}
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={field.placeholder || field.default}
        className={error ? "border-red-500" : ""}
      />
    );
  }

  return (
    <div className="space-y-1.5">
      {labelNode}
      {inputNode}
      {field.helpText && (
        <p className="text-xs text-muted-foreground">{field.helpText}</p>
      )}
      {error && (
        <p className="text-xs text-red-500">This field is required.</p>
      )}
    </div>
  );
}

function Step3CollectInputs({
  hostId,
  inputs,
  onInputChange,
  onNext,
  onBack,
  t,
}: {
  hostId: string;
  inputs: Record<string, string>;
  onInputChange: (id: string, value: string) => void;
  onNext: () => void;
  onBack: () => void;
  t: Translations;
}) {
  const fields = HOST_REQUIRED_INPUTS[hostId] || [];
  const [errors, setErrors] = useState<Record<string, boolean>>({});
  const [validated, setValidated] = useState(false);

  const handleValidate = () => {
    const newErrors: Record<string, boolean> = {};
    for (const f of fields) {
      if (f.required && !inputs[f.id]?.trim()) {
        newErrors[f.id] = true;
      }
    }
    setErrors(newErrors);
    const ok = Object.keys(newErrors).length === 0;
    setValidated(ok);
    return ok;
  };

  const handleNext = () => {
    if (handleValidate()) onNext();
  };

  return (
    <div className="space-y-4">
      <div>
        <h2 className="text-lg font-semibold text-[#1B3A6B] dark:text-slate-100">
          {t.deployStepInputs || "Configure"}
        </h2>
        <p className="text-sm text-muted-foreground">
          Fill in the required credentials and settings for your deployment.
        </p>
      </div>
      {fields.length === 0 ? (
        <p className="text-sm text-muted-foreground">No configuration needed for this host.</p>
      ) : (
        <div className="space-y-4">
          {fields.map((field) => (
            <FieldInput
              key={field.id}
              field={field}
              value={inputs[field.id] ?? field.default ?? ""}
              onChange={(v) => {
                onInputChange(field.id, v);
                if (errors[field.id]) {
                  setErrors((prev) => {
                    const n = { ...prev };
                    delete n[field.id];
                    return n;
                  });
                }
              }}
              error={errors[field.id]}
            />
          ))}
        </div>
      )}
      {validated && Object.keys(errors).length === 0 && (
        <div className="flex items-center gap-2 text-sm text-green-600 dark:text-green-400">
          <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
          All required fields are valid.
        </div>
      )}
      <div className="flex justify-between pt-2">
        <Button variant="outline" onClick={onBack} data-testid="step3-back">
          <ArrowLeft className="h-4 w-4 mr-1" />
          Back
        </Button>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleValidate}
            data-testid="step3-validate"
          >
            Validate
          </Button>
          <Button
            data-testid="step3-next"
            onClick={handleNext}
            className="bg-[#01696F] hover:bg-[#01696F]/90 text-white"
          >
            Continue
            <ChevronRight className="h-4 w-4 ml-1" />
          </Button>
        </div>
      </div>
    </div>
  );
}

// ── Step 4: Review Configuration ─────────────────────────────────────────────

function Step4Review({
  bundle,
  hostId,
  inputs,
  yaml,
  onConfirm,
  onBack,
  onEditStep,
  t,
}: {
  bundle: MarketplaceEntry;
  hostId: string;
  inputs: Record<string, string>;
  yaml: string;
  onConfirm: () => void;
  onBack: () => void;
  onEditStep: (step: WizardStep) => void;
  t: Translations;
}) {
  const { copy, copied } = useCopyToClipboard({ fallbackFilename: "deploy-config", sound: false });
  const hostMeta = HOST_TARGETS.find((h) => h.id === hostId);
  const fields = HOST_REQUIRED_INPUTS[hostId] || [];

  const maskSecret = (field: InputField, val: string) =>
    field.secret ? "••••••" : val || "(not set)";

  return (
    <div className="space-y-5">
      <div>
        <h2 className="text-lg font-semibold text-[#1B3A6B] dark:text-slate-100">
          {t.deployStepReview || "Review"}
        </h2>
        <p className="text-sm text-muted-foreground">
          Confirm your configuration before running the pipeline.
        </p>
      </div>

      {/* Summary row */}
      <div className="grid sm:grid-cols-2 gap-3">
        <Card className="border-[#01696F]/20">
          <CardHeader className="pb-2 pt-3 px-4">
            <div className="flex items-center justify-between">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Bundle
              </CardTitle>
              <Button
                variant="ghost"
                size="sm"
                className="h-6 text-xs text-[#01696F]"
                onClick={() => onEditStep(1)}
                data-testid="review-edit-bundle"
              >
                Edit
              </Button>
            </div>
          </CardHeader>
          <CardContent className="px-4 pb-3">
            <p className="font-medium text-sm">{bundle.name}</p>
            <p className="text-xs text-muted-foreground mt-0.5">{bundle.estimatedCost}</p>
          </CardContent>
        </Card>

        <Card className="border-[#01696F]/20">
          <CardHeader className="pb-2 pt-3 px-4">
            <div className="flex items-center justify-between">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Host Target
              </CardTitle>
              <Button
                variant="ghost"
                size="sm"
                className="h-6 text-xs text-[#01696F]"
                onClick={() => onEditStep(2)}
                data-testid="review-edit-host"
              >
                Edit
              </Button>
            </div>
          </CardHeader>
          <CardContent className="px-4 pb-3">
            <p className="font-medium text-sm flex items-center gap-2">
              {hostIcon(hostId)}
              {hostMeta?.name || hostId}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Inputs summary */}
      {fields.length > 0 && (
        <Card className="border-border">
          <CardHeader className="pb-2 pt-3 px-4">
            <div className="flex items-center justify-between">
              <CardTitle className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Configuration
              </CardTitle>
              <Button
                variant="ghost"
                size="sm"
                className="h-6 text-xs text-[#01696F]"
                onClick={() => onEditStep(3)}
                data-testid="review-edit-inputs"
              >
                Edit
              </Button>
            </div>
          </CardHeader>
          <CardContent className="px-4 pb-3">
            <div className="space-y-1.5">
              {fields.map((f) => (
                <div key={f.id} className="flex items-center justify-between gap-2 text-xs">
                  <span className="text-muted-foreground flex items-center gap-1">
                    {f.secret && <Lock className="h-3 w-3" />}
                    {f.label}
                  </span>
                  <span className="font-mono text-foreground truncate max-w-[200px]">
                    {maskSecret(f, inputs[f.id] ?? f.default ?? "")}
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* YAML code block */}
      <div>
        <div className="flex items-center justify-between mb-1.5">
          <span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Generated YAML Config
          </span>
          <Button
            variant="ghost"
            size="sm"
            className="h-6 text-xs"
            onClick={() => copy(yaml)}
            data-testid="review-copy-yaml"
          >
            {copied ? (
              <>
                <Check className="h-3 w-3 mr-1 text-green-500" />
                Copied
              </>
            ) : (
              <>
                <ClipboardCopy className="h-3 w-3 mr-1" />
                Copy
              </>
            )}
          </Button>
        </div>
        <pre className="bg-muted rounded-lg p-3 text-xs font-mono overflow-x-auto border border-border leading-relaxed text-foreground max-h-60 overflow-y-auto">
          {yaml}
        </pre>
      </div>

      <div className="flex justify-between pt-2">
        <Button variant="outline" onClick={onBack} data-testid="step4-back">
          <ArrowLeft className="h-4 w-4 mr-1" />
          Back
        </Button>
        <Button
          data-testid="step4-confirm"
          onClick={onConfirm}
          className="bg-[#01696F] hover:bg-[#01696F]/90 text-white"
        >
          Run Pipeline
          <Rocket className="h-4 w-4 ml-1.5" />
        </Button>
      </div>
    </div>
  );
}

// ── Step 5: Pipeline ─────────────────────────────────────────────────────────

const STAGE_ICONS: Record<string, string> = {
  collect: "ClipboardCopy",
  validate: "Check",
  smoke: "Zap",
  stress: "Activity",
  simulate: "Play",
  deploy: "Rocket",
  verify: "ShieldCheck",
};

function PipelineRow({
  stageState,
  isDeployStage,
  onPermissionGrant,
  onPermissionDeny,
  deploySkipped,
  hostName,
  t,
}: {
  stageState: PipelineStageState;
  isDeployStage: boolean;
  onPermissionGrant: () => void;
  onPermissionDeny: () => void;
  deploySkipped: boolean;
  hostName: string;
  t: Translations;
}) {
  const StageIcon = resolveIcon(STAGE_ICONS[stageState.step.stage] || "Wrench");
  const { status, step } = stageState;

  return (
    <div className="space-y-2">
      <div
        className={[
          "flex items-center gap-3 p-3 rounded-lg border transition-all",
          status === "running"
            ? "border-[#01696F]/40 bg-[#01696F]/5"
            : status === "passed"
            ? "border-green-500/30 bg-green-500/5"
            : status === "failed"
            ? "border-red-500/30 bg-red-500/5"
            : status === "skipped"
            ? "border-yellow-500/30 bg-yellow-500/5"
            : "border-border bg-card",
        ].join(" ")}
      >
        {/* Icon + status indicator */}
        <div className="relative shrink-0">
          <div
            className={[
              "p-2 rounded-lg",
              status === "running"
                ? "bg-[#01696F] text-white"
                : status === "passed"
                ? "bg-green-500 text-white"
                : status === "failed"
                ? "bg-red-500 text-white"
                : status === "skipped"
                ? "bg-yellow-500 text-white"
                : "bg-muted text-muted-foreground",
            ].join(" ")}
          >
            <StageIcon className="h-4 w-4" />
          </div>
          {status === "running" && (
            <div className="absolute -top-1 -right-1">
              <Loader2 className="h-3 w-3 text-[#01696F] animate-spin" />
            </div>
          )}
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="font-semibold text-sm">{step.label}</span>
            {status === "running" && (
              <Badge variant="secondary" className="text-[10px] bg-[#01696F]/10 text-[#01696F]">
                Running
              </Badge>
            )}
            {status === "passed" && (
              <Badge variant="secondary" className="text-[10px] bg-green-500/10 text-green-600">
                Passed
              </Badge>
            )}
            {status === "failed" && (
              <Badge variant="secondary" className="text-[10px] bg-red-500/10 text-red-600">
                Failed
              </Badge>
            )}
            {status === "skipped" && (
              <Badge variant="secondary" className="text-[10px] bg-yellow-500/10 text-yellow-600">
                Skipped
              </Badge>
            )}
          </div>
          <p className="text-xs text-muted-foreground">{step.description}</p>
          {stageState.message && status === "failed" && (
            <p className="text-xs text-red-500 mt-1">{stageState.message}</p>
          )}
          {stageState.elapsedMs !== undefined && status !== "pending" && (
            <p className="text-xs text-muted-foreground mt-0.5">
              {(stageState.elapsedMs / 1000).toFixed(1)}s
            </p>
          )}
        </div>

        {/* Status icon */}
        <div className="shrink-0">
          {status === "passed" && (
            <CheckCircle2 className="h-5 w-5 text-green-500" />
          )}
          {status === "failed" && <XCircle className="h-5 w-5 text-red-500" />}
          {status === "running" && (
            <Loader2 className="h-5 w-5 text-[#01696F] animate-spin" />
          )}
          {status === "skipped" && (
            <AlertTriangle className="h-5 w-5 text-yellow-500" />
          )}
        </div>
      </div>

      {/* Permission gate for deploy stage */}
      {isDeployStage && status === "running" && !deploySkipped && (
        <Card className="border-orange-500/40 bg-orange-500/5 ml-10">
          <CardContent className="p-4 space-y-3">
            <div className="flex items-start gap-2">
              <AlertTriangle className="h-5 w-5 text-orange-500 shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold text-sm text-orange-700 dark:text-orange-400">
                  {t.deployPermissionTitle || "Permission Required"}
                </p>
                <p className="text-xs text-muted-foreground mt-0.5">
                  {t.deployPermissionDesc ||
                    "This will make real changes to your target environment."}{" "}
                  Target: <strong>{hostName}</strong>
                </p>
              </div>
            </div>
            <div className="flex gap-2 justify-end">
              <Button
                variant="outline"
                size="sm"
                onClick={onPermissionDeny}
                data-testid="deploy-deny"
                className="text-xs"
              >
                Skip Deploy
              </Button>
              <Button
                size="sm"
                onClick={onPermissionGrant}
                data-testid="deploy-confirm"
                className="bg-orange-500 hover:bg-orange-600 text-white text-xs"
              >
                {t.deployConfirmBtn || "I understand, deploy now"}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Skipped message */}
      {isDeployStage && deploySkipped && (
        <div className="ml-10 text-xs text-yellow-600 dark:text-yellow-400 flex items-center gap-1.5">
          <AlertTriangle className="h-3 w-3" />
          {t.deploySkipped || "Deploy skipped — configuration saved"}
        </div>
      )}
    </div>
  );
}

function Step5Pipeline({
  bundle,
  hostId,
  inputs,
  onComplete,
  t,
}: {
  bundle: MarketplaceEntry;
  hostId: string;
  inputs: Record<string, string>;
  onComplete: (elapsed: number, hash: string) => void;
  t: Translations;
}) {
  const hostMeta = HOST_TARGETS.find((h) => h.id === hostId);
  const [stages, setStages] = useState<PipelineStageState[]>(
    PIPELINE_STAGES.map((s) => ({ step: s, status: "pending" as StageStatus }))
  );
  const [currentStageIndex, setCurrentStageIndex] = useState(-1);
  const [deploySkipped, setDeploySkipped] = useState(false);
  const [waitingForPermission, setWaitingForPermission] = useState(false);
  const [startTime] = useState(() => Date.now());
  const [elapsedTime, setElapsedTime] = useState(0);
  const [running, setRunning] = useState(false);
  const runRef = useRef(false);
  const deployGrantedRef = useRef<(() => void) | null>(null);
  const deployDeniedRef = useRef<(() => void) | null>(null);

  // Elapsed timer
  useEffect(() => {
    if (!running) return;
    const interval = setInterval(() => {
      setElapsedTime(Date.now() - startTime);
    }, 200);
    return () => clearInterval(interval);
  }, [running, startTime]);

  const updateStage = useCallback(
    (index: number, update: Partial<PipelineStageState>) => {
      setStages((prev) => {
        const next = [...prev];
        next[index] = { ...next[index], ...update };
        return next;
      });
    },
    []
  );

  const runPipeline = useCallback(async () => {
    if (runRef.current) return;
    runRef.current = true;
    setRunning(true);

    const pStart = Date.now();

    for (let i = 0; i < PIPELINE_STAGES.length; i++) {
      const stage = PIPELINE_STAGES[i];
      setCurrentStageIndex(i);
      updateStage(i, { status: "running" });

      if (stage.stage === "deploy") {
        // Wait for permission grant or deny
        setWaitingForPermission(true);
        await new Promise<void>((resolve) => {
          deployGrantedRef.current = () => {
            setWaitingForPermission(false);
            resolve();
          };
          deployDeniedRef.current = () => {
            setWaitingForPermission(false);
            setDeploySkipped(true);
            updateStage(i, { status: "skipped", elapsedMs: Date.now() - pStart });
            // Skip this stage but continue to verify
            resolve();
          };
        });
        if (!deploySkippedRef.current) {
          // Actually run deploy simulation
          await new Promise((r) => setTimeout(r, stage.estimatedSeconds * 40));
          updateStage(i, { status: "passed", elapsedMs: Date.now() - pStart });
        }
      } else {
        // Auto-run stages with simulated delays
        const delay = Math.min(stage.estimatedSeconds * 50, 2000);
        await new Promise((r) => setTimeout(r, delay));
        updateStage(i, { status: "passed", elapsedMs: Date.now() - pStart });
      }
    }

    const totalMs = Date.now() - pStart;
    setRunning(false);

    // Generate hash
    const hashInput = `${bundle.id}:${hostId}:${JSON.stringify(inputs)}:${totalMs}`;
    const hash = await sha256(hashInput);

    celebrate("Deployment complete! 🎉", "normal");
    playSound("success");
    onComplete(totalMs, hash);
  }, [bundle.id, hostId, inputs, onComplete, updateStage]);

  // Use a ref to track if deploy was skipped (closure issue workaround)
  const deploySkippedRef = useRef(false);
  useEffect(() => {
    deploySkippedRef.current = deploySkipped;
  }, [deploySkipped]);

  useEffect(() => {
    runPipeline();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleGrantPermission = () => {
    if (deployGrantedRef.current) deployGrantedRef.current();
  };
  const handleDenyPermission = () => {
    deploySkippedRef.current = true;
    setDeploySkipped(true);
    if (deployDeniedRef.current) deployDeniedRef.current();
  };

  const progressPct =
    stages.filter((s) => s.status === "passed" || s.status === "skipped").length /
    stages.length *
    100;

  return (
    <div className="space-y-4">
      <div>
        <h2 className="text-lg font-semibold text-[#1B3A6B] dark:text-slate-100">
          {t.deployStepPipeline || "Deploy"}
        </h2>
        <p className="text-sm text-muted-foreground">
          Running deployment pipeline for <strong>{bundle.name}</strong> →{" "}
          <strong>{hostMeta?.name || hostId}</strong>
        </p>
      </div>

      {/* Progress bar */}
      <div className="space-y-1">
        <div className="flex justify-between text-xs text-muted-foreground">
          <span>{Math.round(progressPct)}% complete</span>
          <span>{(elapsedTime / 1000).toFixed(1)}s elapsed</span>
        </div>
        <Progress value={progressPct} className="h-2" />
      </div>

      <div className="space-y-2">
        {stages.map((stageState, i) => (
          <PipelineRow
            key={stageState.step.stage}
            stageState={stageState}
            isDeployStage={stageState.step.stage === "deploy"}
            onPermissionGrant={handleGrantPermission}
            onPermissionDeny={handleDenyPermission}
            deploySkipped={deploySkipped && stageState.step.stage === "deploy"}
            hostName={hostMeta?.name || hostId}
            t={t}
          />
        ))}
      </div>
    </div>
  );
}

// ── Step 6: Complete ──────────────────────────────────────────────────────────

function Step6Complete({
  bundle,
  hostId,
  elapsedMs,
  hash,
  onDeployAnother,
  t,
}: {
  bundle: MarketplaceEntry;
  hostId: string;
  elapsedMs: number;
  hash: string;
  onDeployAnother: () => void;
  t: Translations;
}) {
  const hostMeta = HOST_TARGETS.find((h) => h.id === hostId);

  return (
    <div className="space-y-5 text-center">
      <div className="text-5xl select-none">🎉</div>
      <div>
        <h2 className="text-2xl font-bold text-[#1B3A6B] dark:text-white">
          {t.deploySuccess || "Deployment complete"}
        </h2>
        <p className="text-sm text-muted-foreground mt-1">
          Your bundle is live. Everything was deployed successfully.
        </p>
      </div>

      {/* Summary card */}
      <Card className="text-left border-[#01696F]/20">
        <CardContent className="p-4 space-y-3">
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Bundle</span>
            <span className="font-semibold">{bundle.name}</span>
          </div>
          <Separator />
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Target</span>
            <span className="font-semibold flex items-center gap-1.5">
              {hostIcon(hostId)}
              {hostMeta?.name || hostId}
            </span>
          </div>
          <Separator />
          <div className="flex items-center justify-between text-sm">
            <span className="text-muted-foreground">Deploy time</span>
            <span className="font-semibold">{(elapsedMs / 1000).toFixed(1)}s</span>
          </div>
          <Separator />
          <div className="flex items-start justify-between text-sm gap-3">
            <span className="text-muted-foreground shrink-0">SHA-256 Chain</span>
            <span className="font-mono text-xs text-muted-foreground break-all text-right">
              {hash}
            </span>
          </div>
        </CardContent>
      </Card>

      {/* Action links */}
      <div className="flex flex-col sm:flex-row gap-2 justify-center">
        <Button
          variant="outline"
          asChild
          data-testid="complete-view-audit"
        >
          <a href="/audit">View Audit Log</a>
        </Button>
        <Button
          variant="outline"
          asChild
          data-testid="complete-manage"
        >
          <a href="/logs">Manage Installation</a>
        </Button>
      </div>

      <Button
        data-testid="deploy-another"
        onClick={onDeployAnother}
        className="bg-[#01696F] hover:bg-[#01696F]/90 text-white"
      >
        <RotateCcw className="h-4 w-4 mr-2" />
        {t.deployAnother || "Deploy Another"}
      </Button>
    </div>
  );
}

// ── Main Wizard Component ────────────────────────────────────────────────────

export default function DeployWizard() {
  const { t } = useI18n();

  // Wizard state
  const [step, setStep] = useState<WizardStep>(1);
  const [selectedBundle, setSelectedBundle] = useState<MarketplaceEntry | null>(null);
  const [selectedTarget, setSelectedTarget] = useState<DeployTarget | null>(null);
  const [inputs, setInputs] = useState<Record<string, string>>({});
  const [yaml, setYaml] = useState("");
  const [deployResult, setDeployResult] = useState<{
    elapsedMs: number;
    hash: string;
  } | null>(null);

  const handleInputChange = (id: string, value: string) => {
    setInputs((prev) => ({ ...prev, [id]: value }));
  };

  const handleStep1Next = () => {
    setSelectedTarget(null);
    setInputs({});
    setStep(2);
  };

  const handleStep2Next = () => {
    setInputs({});
    setStep(3);
  };

  const handleStep3Next = () => {
    if (selectedBundle && selectedTarget) {
      const resolvedInputs = { ...inputs };
      // Fill defaults for empty optional fields
      const fields = HOST_REQUIRED_INPUTS[selectedTarget.hostId] || [];
      for (const f of fields) {
        if (!resolvedInputs[f.id] && f.default) {
          resolvedInputs[f.id] = f.default;
        }
      }
      setInputs(resolvedInputs);
      setYaml(buildYaml(selectedBundle, selectedTarget.hostId, resolvedInputs));
    }
    setStep(4);
  };

  const handleStep4Confirm = () => {
    setStep(5);
  };

  const handlePipelineComplete = (elapsedMs: number, hash: string) => {
    setDeployResult({ elapsedMs, hash });
    setStep(6);
  };

  const handleDeployAnother = () => {
    setSelectedBundle(null);
    setSelectedTarget(null);
    setInputs({});
    setYaml("");
    setDeployResult(null);
    setStep(1);
  };

  const handleEditStep = (targetStep: WizardStep) => {
    setStep(targetStep);
  };

  return (
    <div className="min-h-screen bg-background px-4 py-8">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="text-center mb-6">
          <div className="flex items-center justify-center gap-2 mb-2">
            <div className="p-2 rounded-lg bg-[#01696F] text-white">
              <Rocket className="h-5 w-5" />
            </div>
            <h1 className="text-2xl font-bold text-[#1B3A6B] dark:text-white">
              {t.deployWizardTitle || "1-Click Deploy"}
            </h1>
          </div>
          <p className="text-sm text-muted-foreground">
            {t.deployWizardSubtitle ||
              "Select a bundle, configure your target, and deploy in minutes."}
          </p>
        </div>

        {/* Step indicator */}
        <StepIndicator current={step} t={t} />

        {/* Step content */}
        <Card className="shadow-sm border-border">
          <CardContent className="p-6">
            {step === 1 && (
              <Step1SelectBundle
                selected={selectedBundle}
                onSelect={setSelectedBundle}
                onNext={handleStep1Next}
                t={t}
              />
            )}
            {step === 2 && selectedBundle && (
              <Step2ChooseHost
                bundle={selectedBundle}
                selected={selectedTarget}
                onSelect={setSelectedTarget}
                onNext={handleStep2Next}
                onBack={() => setStep(1)}
                t={t}
              />
            )}
            {step === 3 && selectedTarget && (
              <Step3CollectInputs
                hostId={selectedTarget.hostId}
                inputs={inputs}
                onInputChange={handleInputChange}
                onNext={handleStep3Next}
                onBack={() => setStep(2)}
                t={t}
              />
            )}
            {step === 4 && selectedBundle && selectedTarget && (
              <Step4Review
                bundle={selectedBundle}
                hostId={selectedTarget.hostId}
                inputs={inputs}
                yaml={yaml}
                onConfirm={handleStep4Confirm}
                onBack={() => setStep(3)}
                onEditStep={handleEditStep}
                t={t}
              />
            )}
            {step === 5 && selectedBundle && selectedTarget && (
              <Step5Pipeline
                key={`pipeline-${selectedBundle.id}-${selectedTarget.hostId}`}
                bundle={selectedBundle}
                hostId={selectedTarget.hostId}
                inputs={inputs}
                onComplete={handlePipelineComplete}
                t={t}
              />
            )}
            {step === 6 && selectedBundle && selectedTarget && deployResult && (
              <Step6Complete
                bundle={selectedBundle}
                hostId={selectedTarget.hostId}
                elapsedMs={deployResult.elapsedMs}
                hash={deployResult.hash}
                onDeployAnother={handleDeployAnother}
                t={t}
              />
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
